### ISSUE TITLE
ModuleNotFoundError: No modue named '_cffi_backend'

### ISSUE THREAD

**Issue by wwjang** [sco-edge/E2FL#1]
Traceback (most recent call last):
  File "/home/wwjang/E2FL/test_wrls-power.py", line 10, in <module>
    import paramiko
  File "/usr/lib/python3/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/lib/python3/dist-packages/paramiko/ed25519key.py", line 17, in <module>
    import bcrypt
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt
ModuleNotFoundError: No module named '_cffi_backend'

**Comment by wwjang** [comment]
$ python3.10 -m pip install cffi
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cffi in /.local/lib/python3.10/site-packages (1.16.0)
Requirement already satisfied: pycparser in /.local/lib/python3.10/site-packages (from cffi) (2.22)
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.36ubuntu1 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-debian or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by wwjang** [comment]
according to https://community.letsencrypt.org/t/modulenotfounderror-no-module-named-cffi-backend/137535/13

pip install -U cffi

**Comment by wwjang** [comment]
https://stackoverflow.com/questions/75272737/error-invalid-version-0-23ubuntu1-package-distro-info

pip uninstall -y distro-info
pip install distro-info==1.0

**Comment by wwjang** [comment]
https://stackoverflow.com/questions/70570309/pkgresourcesdeprecationwarning-0-1-36ubuntu1-is-an-invalid-version-has-anyone

sudo apt-get remove --auto-remove python3-debian

**Comment by wwjang** [comment]
Resolve this issue by installing cffi on sudo python and update it.
